// Plain-English definitions for Lichess puzzle theme tags, keyed by the raw
// theme id (same casing as themeLabels.js) so callers can look up straight
// from currentThemes without any reverse-mapping from the formatted display
// text. Not every theme Lichess emits has an entry here (e.g. length/rating
// tags like "short", "long", "master", "oneMove" aren't tactical motifs) --
// callers should have a fallback for a missing key, not treat it as unreachable.
export const THEME_DEFINITIONS = {
  advancedPawn: "A pawn that's pushed deep into enemy territory, close enough to threaten promotion.",
  advantage: "A move that swings the position solidly in your favor, though not a total knockout.",
  anastasiaMate: "A knight and rook (or queen) trap the enemy king against the board's edge.",
  arabianMate: "A knight and rook corner the enemy king together at the edge of the board.",
  attackingF2F7: "A tactic aimed at the weak f2/f7 pawn, common in fast early-game attacks.",
  attraction: "A sacrifice or trade that lures an enemy piece onto a bad square, setting up the real blow.",
  backRankMate: "Checkmate on the back rank because the king's own pieces block its escape.",
  bishopEndgame: "An endgame where only bishops and pawns remain on the board.",
  bodenMate: "Two bishops on crossing diagonals deliver mate to a boxed-in king.",
  castling: "Getting the king to safety while bringing a rook into play.",
  capturingDefender: "Removing the piece that's guarding something, so the now-undefended piece can be taken.",
  crushing: "The opponent handed you a big mistake — cash in for a decisive advantage.",
  doubleBishopMate: "Two bishops on neighboring diagonals deliver mate to a king with no escape squares.",
  dovetailMate: "The queen mates a king whose only two flight squares are blocked by its own pieces.",
  equality: "Clawing back from a losing spot to reach a draw or roughly even position.",
  kingsideAttack: "An assault on the enemy king after it castled kingside.",
  clearance: "A move that vacates a square, file, or diagonal to make room for the real tactic.",
  defensiveMove: "The one precise move needed to avoid losing material or ground.",
  deflection: "Luring a defending piece away from the job it's doing.",
  discoveredAttack: "Moving one piece out of the way unleashes an attack from a piece behind it.",
  doubleCheck: "A discovered attack where both the moved piece and the revealed piece check the king at once.",
  endgame: "A tactic that happens in the final phase of the game.",
  enPassant: "A special pawn capture rule kicking off the tactic.",
  exposedKing: "A king with too little cover around it, ripe for attack.",
  fork: "One move, two (or more) enemy pieces under attack at once.",
  hangingPiece: "An enemy piece that's undefended or under-defended — just take it.",
  hookMate: "Mate delivered with a rook, knight, and pawn boxing in the king, aided by an enemy pawn.",
  interference: "Dropping a piece between two enemy pieces so one (or both) loses its defender.",
  intermezzo: "A surprise in-between move that forces a response before the expected sequence continues.",
  killBoxMate: "A rook and queen trap the king in a tight 3x3 box near the board's edge.",
  vukovicMate: "A rook delivers mate while a knight cuts off the king's escape squares.",
  knightEndgame: "An endgame where only knights and pawns remain.",
  mate: "The puzzle ends in checkmate.",
  mateIn1: "Find checkmate in a single move.",
  mateIn2: "Force checkmate in exactly two moves.",
  mateIn3: "Force checkmate in exactly three moves.",
  mateIn4: "Force checkmate in exactly four moves.",
  mateIn5: "A longer forced mating sequence — think several moves ahead.",
  middlegame: "A tactic from the game's middle phase.",
  opening: "A tactic that shows up early, in the opening phase.",
  pawnEndgame: "An endgame with only pawns (and kings) left.",
  pin: "An enemy piece can't move without exposing something more valuable behind it.",
  promotion: "Push a pawn all the way to promote it.",
  queenEndgame: "An endgame with only queens and pawns remaining.",
  queenRookEndgame: "An endgame with only queens, rooks, and pawns remaining.",
  queensideAttack: "An assault on the enemy king after it castled queenside.",
  quietMove: "A move that isn't a check or capture, but quietly sets up an unstoppable threat.",
  rookEndgame: "An endgame with only rooks and pawns remaining.",
  sacrifice: "Giving up material on purpose to force a bigger gain a few moves later.",
  skewer: "The reverse of a pin — a valuable piece is attacked, moves, and exposes a lesser piece behind it.",
  smotheredMate: "A knight delivers mate to a king that's boxed in by its own pieces.",
  trappedPiece: "A piece with nowhere safe to run — it's going to be captured.",
  underPromotion: "Promoting to a knight, bishop, or rook instead of a queen — and it's the right call.",
  xRayAttack: "A piece attacks or defends a square right through an enemy piece standing in the way.",
  zugzwang: "The opponent has to move, but every option makes their position worse.",
}
